# Generated by Django 4.2.5 on 2024-12-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FileAdmin", "0007_filedata_ipfs_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetData",
            fields=[
                (
                    "asset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_number", models.CharField(max_length=64)),
                ("transaction_id", models.CharField(max_length=64)),
                ("token_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="FileAdmin.filedata",
                    ),
                ),
            ],
        ),
    ]
