# Generated by Django 4.2.5 on 2024-11-21 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractProfile",
            fields=[
                (
                    "contract_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_address", models.CharField(max_length=64, null=True)),
                ("contract_abi", models.TextField()),
                ("contract_bytecode", models.TextField()),
                ("owner_address", models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
