# Generated by Django 4.2.5 on 2024-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
