# Generated by Django 4.2.5 on 2024-10-18 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AccountAdmin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="id",
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="public_address",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Wallet address must be alphanumeric.",
                        regex="^[a-zA-Z0-9]*$",
                    )
                ],
            ),
        ),
    ]
