# Generated by Django 4.2.5 on 2024-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FileAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="file_hash_updated",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
