# Generated by Django 4.2.5 on 2024-10-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AccountAdmin", "0002_remove_accountprofile_id_and_more"),
        ("FileAdmin", "0002_filedata_file_hash_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="public_address",
            field=models.ForeignKey(
                default=273748755476352112117436412804905291858580304972,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_address",
                to="AccountAdmin.accountprofile",
            ),
            preserve_default=False,
        ),
    ]
