# Generated by Django 4.2.5 on 2024-10-18 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FileAdmin", "0003_filedata_public_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filedata",
            name="public_address",
        ),
    ]
