# Generated by Django 4.2.5 on 2024-10-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AccountAdmin", "0003_accountprofile_id_and_more"),
        ("FileAdmin", "0004_remove_filedata_public_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="user_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_data",
                to="AccountAdmin.accountprofile",
            ),
            preserve_default=False,
        ),
    ]
