# Generated by Django 4.2.5 on 2024-10-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FileAdmin", "0005_filedata_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedata",
            name="user_address",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
