# Generated by Django 4.2.5 on 2024-11-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FileAdmin", "0006_alter_filedata_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="ipfs_hash",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
